image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git (ветка, которую собираем/хотим интегрировать. Если )
              # Если в локальном репозитории 2 ветки - мастер и "Фича ветка" и мы пушим в удаленный репо
              # вторую ветку, то  УЗНАТЬ что будет (наверное ошибка)
build: off  # будем использовать свой скрипт сборки

build_script:
  - chmod +x gradlew
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации